INSERT INTO SYS_JOB (ID, NAME, PARENT_ID, PARENT_IDS, ICON, WEIGHT, IS_SHOW) VALUES (1, '中公网', 0, '0/', null, 100, true);
INSERT INTO SYS_JOB (ID, NAME, PARENT_ID, PARENT_IDS, ICON, WEIGHT, IS_SHOW) VALUES (2, '公司副总', 1, '0/1/', null, 100, true);
INSERT INTO SYS_JOB (ID, NAME, PARENT_ID, PARENT_IDS, ICON, WEIGHT, IS_SHOW) VALUES (3, '技术总监', 2, '0/1/2/', null, 100, true);
INSERT INTO SYS_JOB (ID, NAME, PARENT_ID, PARENT_IDS, ICON, WEIGHT, IS_SHOW) VALUES (4, '技术经理', 3, '0/1/2/3/', null, 100, true);
INSERT INTO SYS_JOB (ID, NAME, PARENT_ID, PARENT_IDS, ICON, WEIGHT, IS_SHOW) VALUES (5, '普通员工', 4, '0/1/2/3/4/', null, 100, true);
